name: learn_world
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.5
  firebase_core: ^2.14.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.2
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  equatable: ^2.0.5
  http: ^1.0.0
  flutter_svg: ^2.0.7
  markdown_widget: ^2.2.0
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.4.0
  # flutter_native_splash: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  # flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/constants/assets/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80) flutter packages pub run build_runner build

  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "assets/icons/logo_bg.png"
  adaptive_icon_foreground: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  # flutter pub run flutter_launcher_icons
