// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV56aJtLXh17b16uDXfHhcYGlyN4wi4yE',
    appId: '1:730093015617:web:5a13c82f4fafccf7656cc0',
    messagingSenderId: '730093015617',
    projectId: 'learn-world-8e6d4',
    authDomain: 'learn-world-8e6d4.firebaseapp.com',
    storageBucket: 'learn-world-8e6d4.appspot.com',
    measurementId: 'G-LDBF5GWK9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoDIM7LjeYLZJWPc48UPF1ZohpBFFPTQI',
    appId: '1:730093015617:android:959f9c467c349ea6656cc0',
    messagingSenderId: '730093015617',
    projectId: 'learn-world-8e6d4',
    storageBucket: 'learn-world-8e6d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJNXR6RrZfotJIISc30Om7A4cxxsxWBk',
    appId: '1:730093015617:ios:903f25728cc4026b656cc0',
    messagingSenderId: '730093015617',
    projectId: 'learn-world-8e6d4',
    storageBucket: 'learn-world-8e6d4.appspot.com',
    iosClientId: '730093015617-cp98hcjrde0tnvt9jgn6rajo625lejkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkJNXR6RrZfotJIISc30Om7A4cxxsxWBk',
    appId: '1:730093015617:ios:da07381e2571aa30656cc0',
    messagingSenderId: '730093015617',
    projectId: 'learn-world-8e6d4',
    storageBucket: 'learn-world-8e6d4.appspot.com',
    iosClientId: '730093015617-8mt7e4pgaaanvfthib4a0shch6jg1ctr.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnWorld.RunnerTests',
  );
}
